name: notes_app
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./tsconfig.json:/app/tsconfig.json
      - ./vite.config.ts:/app/vite.config.ts
    ports:
      - '5174:5174'
    networks:
      - notes

networks:
  notes:
    driver: bridge
    external: true
